### ISSUE TITLE
Error for next_page() on AnimeRanking

### ISSUE THREAD

**Issue by Seros** [Skylake-dev/mal.py#1]
When I try to call next_page() for a AnimeRanking object it throws following error:
`TypeError: __init__() missing 1 required positional argument: 'type'`
My code:
```python
from mal import client
from mal.enums import AnimeRankingType,Field

mal_client = client.Client(client_id='xxx')

results = mal_client.get_anime_ranking(ranking_type=AnimeRankingType.tv, limit=500, fields=Field.all_anime())
results = results.next_page(mal_client)
```

**Comment by Skylake-dev** [comment]
Hello, thanks for reporting this issue.
I understand why this happens and i am going to fix it soon.

**Comment by Skylake-dev** [comment]
I just release v0.6.1 addressing this issue, now it should work properly
