### ISSUE TITLE
KeyError for 'main_picture' on related anime

### ISSUE THREAD

**Issue by Seros** [Skylake-dev/mal.py#2]
When I loop over the Top 500 anime to fetch all their fields I get a KeyError for the main_picture for rank 169 "'Sasaki to Miyano'" with the id 44055. Fetching its related anime leads to the error because one of them, "Hirano to Kagiura" with the id 52364 has no main picture returned by the api.

**Comment by Skylake-dev** [comment]
Can you post the code that you are using?
Anyway i think i got the problem

**Comment by Skylake-dev** [comment]
should be fixed in b666c57ce97048a15e95700a9bcc4c57e3a3aa5b

**Comment by Seros** [comment]
Yeah this works!
