### ISSUE TITLE
I got a error in query limit in anime_search method

### ISSUE THREAD

**Issue by GabrielNX** [Skylake-dev/mal.py#4]
Some anime with names are much longer than 64 characters so, how fix this issue?

ValueError: query parameter needs to be between 3 and 64 characters long

**Comment by Skylake-dev** [comment]
Hello @GabrielNX,

unfortunately this is a limitation on the API side, queries longer than 64 characters result in an http error.
You have to truncate the title to 64 characters if it is longer. 

I could make the method truncate the name on its own for ease of use, and log when this happens.

**Comment by Skylake-dev** [comment]
You can now enable the truncation automatically in version 0.9.0.

```python
from mal.client import Client

c = Client('client_id')
c.auto_truncate = True
```

Also the doc build should be fixed on readthedocs, you can find it [here](https://malpy.readthedocs.io/en/latest/index.html)
